# Options
set -g prefix C-a
set -g mouse on
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Keybinds
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Sane split commands
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# I'm a vim user!
setw -g mode-keys vi
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

# List of colorschemes

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
